#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parent
INPUT_JSON = BASE_DIR / "area.json"
OUTPUT_DIR = BASE_DIR / "output"
OUTPUT_FILE = OUTPUT_DIR / "build.mcfunction"


def block_name(name: str) -> str:
    if ":" in name:
        return name
    return f"minecraft:{name}"


def fill_cmd(a: list[int], b: list[int], material: str) -> str:
    return f"fill {a[0]} {a[1]} {a[2]} {b[0]} {b[1]} {b[2]} {block_name(material)}"


def generate_house(area: dict[str, Any]) -> list[str]:
    x1, y1, z1 = area["from"]
    x2, y2, z2 = area["to"]
    floor = area["material_floor"]
    wall = area["material_wall"]
    roof = area["material_roof"]

    return [
        f"# {area['name']}",
        fill_cmd([x1, y1, z1], [x2, y1, z2], floor),
        fill_cmd([x1, y1 + 1, z1], [x2, y2 - 1, z1], wall),
        fill_cmd([x1, y1 + 1, z2], [x2, y2 - 1, z2], wall),
        fill_cmd([x1, y1 + 1, z1], [x1, y2 - 1, z2], wall),
        fill_cmd([x2, y1 + 1, z1], [x2, y2 - 1, z2], wall),
        fill_cmd([x1, y2, z1], [x2, y2, z2], roof),
        f"setblock {x1 + 5} {y1 + 1} {z1} minecraft:air",
        ""
    ]


def generate_road(area: dict[str, Any]) -> list[str]:
    return [
        f"# {area['name']}",
        fill_cmd(area["from"], area["to"], area["material"]),
        ""
    ]


def generate_plaza(area: dict[str, Any]) -> list[str]:
    x1, y1, z1 = area["from"]
    x2, y2, z2 = area["to"]
    material = area["material"]
    return [
        f"# {area['name']}",
        fill_cmd([x1, y1, z1], [x2, y1, z2], material),
        "# 屋台ラフ",
        fill_cmd([-2, y1 + 1, -10], [1, y1 + 2, -7], "oak_planks"),
        fill_cmd([8, y1 + 1, -10], [11, y1 + 2, -7], "oak_planks"),
        fill_cmd([-2, y1 + 1, 7], [1, y1 + 2, 10], "oak_planks"),
        fill_cmd([8, y1 + 1, 7], [11, y1 + 2, 10], "oak_planks"),
        ""
    ]


def generate_church(area: dict[str, Any]) -> list[str]:
    x1, y1, z1 = area["from"]
    x2, y2, z2 = area["to"]
    floor = area["material_floor"]
    wall = area["material_wall"]
    roof = area["material_roof"]

    return [
        f"# {area['name']}",
        fill_cmd([x1, y1, z1], [x2, y1, z2], floor),
        fill_cmd([x1, y1 + 1, z1], [x2, y2 - 1, z1], wall),
        fill_cmd([x1, y1 + 1, z2], [x2, y2 - 1, z2], wall),
        fill_cmd([x1, y1 + 1, z1], [x1, y2 - 1, z2], wall),
        fill_cmd([x2, y1 + 1, z1], [x2, y2 - 1, z2], wall),
        fill_cmd([x1, y2, z1], [x2, y2, z2], roof),
        "# 礼拝堂入口",
        f"setblock {x1 + 8} {y1 + 1} {z1} minecraft:air",
        f"setblock {x1 + 8} {y1 + 2} {z1} minecraft:air",
        "# 地下入口ラフ",
        fill_cmd([x1 + 6, y1, z2 - 2], [x1 + 10, y1, z2 - 1], "blackstone"),
        ""
    ]


def main() -> None:
    data = json.loads(INPUT_JSON.read_text(encoding="utf-8"))
    lines: list[str] = [
        "# Meritocracia Minecraft Prototype",
        "# generated by tools/minecraft_build_tool/generate.py",
        ""
    ]

    generators = {
        "house": generate_house,
        "road": generate_road,
        "plaza": generate_plaza,
        "church": generate_church,
    }

    for area in data["areas"]:
        area_type = area["type"]
        if area_type not in generators:
            raise ValueError(f"Unknown area type: {area_type}")
        lines.extend(generators[area_type](area))

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
